# Generated by Django 5.0.14 on 2025-07-16 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('website', models.CharField(max_length=255, null=True, unique=True)),
                ('about', models.TextField(null=True)),
                ('values', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255, unique=True)),
                ('province', models.CharField(max_length=255, unique=True)),
                ('country', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=4096, unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('qualifications', models.TextField(null=True)),
                ('responsibilities', models.TextField(null=True)),
                ('preferred_qualifications', models.TextField(null=True)),
                ('posted_date', models.DateField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='jobs.company')),
                ('locations', models.ManyToManyField(to='jobs.location')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('applied_date', models.DateField()),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='jobs.job')),
            ],
        ),
    ]
