# Generated by Django 5.2.4 on 2025-07-17 22:18

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(choices=[('qualifications', 'Qualifications'), ('responsibilities', 'Responsibilities'), ('preferred_qualifications', 'Preferred Qualifications')], max_length=32)),
                ('line_number', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='jobs.job')),
            ],
            options={
                'unique_together': {('job', 'field', 'line_number')},
            },
        ),
    ]
