# Generated by Django 5.0.14 on 2025-07-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_application_id_alter_company_id_alter_job_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='province',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('city', 'province', 'country')},
        ),
    ]
