# Generated by Django 5.2.4 on 2025-07-28 22:52

import utils.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobembedding',
            name='embedding',
            field=utils.models.DefaultVectorField(dimensions=1536),
        ),
    ]
