# Generated by Django 5.0.14 on 2025-07-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_title_alter_location_city_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('title', 'company'), name='unique_job_title_company'),
        ),
    ]
