# Generated by Django 5.0.14 on 2025-07-16 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_location_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='job',
            name='unique_job_title_company',
        ),
    ]
