# Generated by Django 5.0.14 on 2025-07-16 23:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_job_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostingSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='url',
        ),
        migrations.CreateModel(
            name='JobPostingLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=4096, unique=True)),
                ('html_page', models.FileField(upload_to='')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('redirect', 'Redirect'), ('in_progress', 'In Progress'), ('not_applicable', 'Not Applicable')], default='applied', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('job_posting_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobpostingsite')),
            ],
        ),
    ]
