# Generated by Django 5.0.14 on 2025-07-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_jobpostingsite_remove_job_url_jobpostinglink'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default='ca', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
