# Generated by Django 5.0.14 on 2025-07-17 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostinglink',
            name='status',
        ),
    ]
