# Generated by Django 5.2.4 on 2025-07-31 23:24

import django.db.models.deletion
import utils.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        ('jobs', '0004_alter_jobembedding_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
                ('embedding', utils.models.DefaultVectorField(default=None, dimensions=1536, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceKeyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiences.experience')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiences.keyword')),
            ],
            options={
                'unique_together': {('experience', 'keyword')},
            },
        ),
        migrations.AddField(
            model_name='experience',
            name='keywords',
            field=models.ManyToManyField(through='experiences.ExperienceKeyword', to='experiences.keyword'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('locations', models.ManyToManyField(to='jobs.location')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('content', models.TextField(default='')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiences.organization')),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiences.project'),
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.application')),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='chats.session')),
                ('projects', models.ManyToManyField(to='experiences.project')),
            ],
        ),
    ]
