# Generated by Django 5.2.4 on 2025-07-17 22:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('keywords', models.ManyToManyField(to='experiences.keyword')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='experiences.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiences.project')),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('application', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.application')),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='chats.session')),
                ('projects', models.ManyToManyField(to='experiences.project')),
            ],
        ),
    ]
