# Generated by Django 5.0.14 on 2025-07-16 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceGroup',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('application', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.application')),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='chats.session')),
                ('experience_groups', models.ManyToManyField(to='experiences.experiencegroup')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('experience_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiences.experiencegroup')),
                ('keywords', models.ManyToManyField(to='experiences.keyword')),
            ],
        ),
    ]
