# Generated by Django 5.2.4 on 2025-07-28 22:52

import utils.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_project_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='embedding',
            field=utils.models.DefaultVectorField(default=None, dimensions=1536, null=True),
        ),
    ]
