name: Trigger auto deployment for aca-portfolio-prod

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/aca-portfolio-prod-AutoDeployTrigger-5f461528-e429-4116-b926-eae166c5d099.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ACAPORTFOLIOPROD_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}backend
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.ACAPORTFOLIOPROD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACAPORTFOLIOPROD_REGISTRY_PASSWORD }}
          containerAppName: aca-portfolio-prod
          resourceGroup: rg-portfolio-omananddev
          imageToBuild: omananddev/omananddev/portfolio-backend:${{ github.sha }}
          
            

     

