name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - "**"
    paths:
      - "frontend/**"
      - ".github/workflows/azure-static-web-apps-polite-meadow-0cdfa0b0f.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/azure-static-web-apps-polite-meadow-0cdfa0b0f.yml"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          cd frontend/portfolio
          npm ci

      - name: Build Next.js static site
        run: |
          cd frontend/portfolio
          npm run build

      - name: Install SWA CLI
        run: npm install -g @azure/static-web-apps-cli

      - name: Deploy to Azure Static Web Apps using SWA CLI
        env:
          SWA_CLI_DEPLOYMENT_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_MEADOW_0CDFA0B0F }}
        run: |
          cd frontend/portfolio
          swa deploy ./out \
            --deployment-token $SWA_CLI_DEPLOYMENT_TOKEN
